sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master
env:
- DOCKER_IMAGE=jkrajnc11/sharycar-microservice-recommendations

script:
- mvn clean install -U
- docker build -t "$DOCKER_IMAGE" .

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push "$DOCKER_IMAGE"